contentful/ui-extensions-sdk

.npmignore, CHANGELOG, README.md, doc/widget-api-frontend.md, lib/api/index.js, lib/api/setup.js, package.json, test/unit/setup.spec.js, webpack.config.js
=> Prepare NPM release

README.md
The one initially proposed doesn't work out of the box (HTTPS required)
=> Update git clone command note

Makefile, karma.conf.js, package.json, test/unit/entry.spec.js
Installation of SlimerJS package keeps failing
=> Replace SlimerJS with PhantomJS

kss-config.json, lib/style/styleguide.md
=> Fix links in styleguide

docs/cf-extension.css, docs/cf-widget-api.css, docs/styleguide/public/kss.less, lib/style/buttons.styl, lib/style/form.styl
For improved accessability all interactive elements should have outlines in their focused/active state
=> feature(Add default outlines to all interactive elements)

lib/space.js, test/unit/space.spec.js
Adding the corresponding proxies of the image upload methods we've added to the web app
=> Add image upload methods

package.json, typings.d.ts
* Better DX without Typescript
* Type-safety using Typescript
=> Added TS typings

.circleci/config.yml, .nvmrc, package-lock.json, package.json, test/integration/index.js
Preparation for integration tests.
=> CI for integration tests

.eslintrc.json, lib/api.js, lib/channel.js, lib/dialogs.js, lib/editor.js, lib/entry.js, lib/field-locale.js, lib/field.js, lib/initialize.js, lib/navigator.js, lib/signal.js, lib/space.js, lib/window.js, package-lock.json, package.json, test/cypress/support/commands.js, test/cypress/utils/paths.js, test/helpers.js, test/integration/index.js, test/integration/local.js, test/integration/utils.js, test/unit/api.spec.js, test/unit/channel.spec.js, test/unit/field-locale.spec.js, test/unit/field.spec.js, test/unit/initialize.spec.js, test/unit/signal.spec.js, test/unit/window.spec.js
To make it aligned with other codebases.
=> Setup prettier as a precommit hook and prettify codebase

docs/run-integration-tests.md, test/cypress/support/commands.js, test/integration/index.js, test/integration/local.js
Fix inability to run tests locally
=> Change env variable name for integration suite

test/cypress/integration/field-extension.spec.js, test/cypress/utils/paths.js, test/extensions/test-page-extension/.babelrc, test/extensions/test-page-extension/.gitignore, test/extensions/test-page-extension/extension.json, test/extensions/test-page-extension/package-lock.json, test/extensions/test-page-extension/package.json, test/extensions/test-page-extension/src/index.css, test/extensions/test-page-extension/src/index.html, test/extensions/test-page-extension/src/index.js, test/integration/tasks/build-extensions.js, test/integration/tasks/create-configuration-files.js, test/integration/tasks/deploy-extensions.js
This adds page extension integration tests. This is blocked by #212
=> Adding in page extensions integration tests

test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/sidebar-extension.spec.js, test/extensions/test-extension/src/entry-editor-extension.js, test/extensions/test-extension/src/index.js, test/extensions/test-extension/src/sidebar-extension.js
Check that sidebar extension is rendered.
=> Added sidebar cypress test

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-page-extension-test.js, test/cypress/integration/sidebar-extension.spec.js, test/cypress/support/commands.js, test/extensions/test-extension/src/components/index.js, test/extensions/test-extension/src/components/open-dialog-extension-button.js, test/extensions/test-extension/src/components/open-page-extension-button.js, test/extensions/test-extension/src/dialog-extension.js, test/extensions/test-extension/src/entry-editor-extension.js, test/extensions/test-extension/src/field-extension.js, test/extensions/test-extension/src/index.js, test/extensions/test-extension/src/page-extension.js, test/extensions/test-extension/src/sidebar-extension.js
Added integration tests for opening page extensions
=> EXT-968 test for opening page extensions

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-dialog-extension-test.js, test/cypress/integration/reusable/open-page-extension-test.js, test/cypress/integration/sidebar-extension.spec.js, test/extensions/test-extension/src/dialog-extension.js, test/extensions/test-extension/src/entry-editor-extension.js, test/extensions/test-extension/src/field-extension.js, test/extensions/test-extension/src/page-extension.js, test/extensions/test-extension/src/sidebar-extension.js
=> Test dialogs.openExtension method

test/constants.js, test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-dialog-extension-test.js, test/cypress/integration/reusable/open-entry-test.js, test/cypress/integration/reusable/open-page-extension-test.js, test/cypress/integration/sidebar-extension.spec.js, test/cypress/support/commands.js, test/cypress/support/index.js, test/extensions/test-extension/src/components/index.js, test/extensions/test-extension/src/components/open-dialog-extension-button.js, test/extensions/test-extension/src/components/open-entry-button.js, test/extensions/test-extension/src/components/open-page-extension-button.js, test/extensions/test-extension/src/dialog-extension.js, test/extensions/test-extension/src/entry-editor-extension.js, test/extensions/test-extension/src/field-extension.js, test/extensions/test-extension/src/page-extension.js, test/extensions/test-extension/src/sidebar-extension.js
Increase integration tests coverage
=> Add tests for `navigator.openEntry` method

test/constants.js, test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-asset-test.js, test/cypress/integration/sidebar-extension.spec.js, test/cypress/utils/paths.js, test/extensions/test-extension/package-lock.json, test/extensions/test-extension/src/components/index.js, test/extensions/test-extension/src/components/open-asset-button.js, test/extensions/test-extension/src/dialog-extension.js, test/extensions/test-extension/src/entry-editor-extension.js, test/extensions/test-extension/src/field-extension.js, test/extensions/test-extension/src/page-extension.js, test/extensions/test-extension/src/sidebar-extension.js
Increase coverage of integration tests.
=> Added test for openAsset method

.circleci/config.yml, cypress.json, package-lock.json, package.json, test/integration/index.js
Hopefully I'm making it more stable and provide a better report.
=> Integration improvements

.circleci/config.yml, test/cypress/integration/page-extension.spec.js, test/integration/run-script.js
=> Improve tests stability

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/fixtures/locales-data.json, test/cypress/integration/fixtures/user-data.json, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-sdk-locales-data-test.js, test/cypress/integration/reusable/open-sdk-user-data-test.js, test/cypress/integration/sidebar-extension.spec.js
- Added test, which verifies, that sdk.locales static methods have expected values
- Refactored open-sdk-locales-data-test.js.
=> Added test on sdk.locales static methods values

dist/cf-extension.css, docs/cf-extension.css, docs/cf-widget-api.css
Removed Avenir from all legacy styles that were used in pre-Forma era.
=> Removed Avenir from all legacy styles

package-lock.json, package.json
=> Bump to 3.9.2

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/fixtures/content-type-data/entry-editor-ext.json, test/cypress/integration/fixtures/content-type-data/field-ext.json, test/cypress/integration/fixtures/content-type-data/sidebar-ext.json, test/cypress/integration/fixtures/entry-data.json, test/cypress/integration/fixtures/ids-data.json, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-sdk-entry-data-test.js, test/cypress/integration/sidebar-extension.spec.js
Added test, which verifies, that sdk.ids static methods have expected values
=> Added test on sdk.ids static methods values

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/sidebar-extension.spec.js, test/cypress/utils/verify-location.js
Added tests, which verifies sdk.location.is method is true for all extension types.
=> Added sdk.location.is method tests

test/integration/local.js
=> Better logging for env variables

test/integration/index.js, test/integration/local.js
=> Remove pat from logs

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/fixtures/content-type-data/field-ext.json, test/cypress/integration/fixtures/parameters.json, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-dialog-extension-test.js, test/cypress/integration/reusable/open-page-extension-test.js, test/cypress/integration/reusable/open-sdk-parameters-test.js, test/cypress/integration/sidebar-extension.spec.js, test/cypress/utils/verify-parameters.js, test/extensions/test-extension/extension.json, test/extensions/test-extension/package.json
Tests for installation, instance and invocation parameters have been added.
=> add test sdk parameters methods

.circleci/config.yml
=> Run tests nighly

.circleci/config.yml
=> Run nightly at 2:22am

package.json, typings.d.ts
Apply codestyle for type definitions
=> chore: prettify typings file

package-lock.json, package.json, typings.d.ts
Added new parameters to `dialogs.openExtension` type definition.
=> feat(dialogs): added new available params to typescript defs

typings.d.ts
=> Improve typescript typings

lib/api.js, lib/app.js, lib/dialogs.js, lib/locations.js, package-lock.json, package.json, test/unit/api.spec.js, test/unit/app.spec.js, test/unit/dialogs.spec.js, typings.d.ts
Introduce `app.sdk`. Patch bump for the transition period. Minor version bump will follow (for stabilizing the API fully).
=> "App" namespace

lib/api.js, package-lock.json, package.json, test/cypress/integration/reusable/open-sdk-locales-data-test.js, test/extensions/test-extension/package-lock.json, test/unit/api.spec.js, typings.d.ts
Provide more useful information about locales that might be needed in some extensions.
=> feat(locales): expose locales.optional and locales.direction

typings.d.ts
Use generics in all CMA methods to simplify customization.
Fix some incorrect typings.
=> feat(typings): improve typescript support

cypress.json, lib/navigator.js, package-lock.json, package.json, test/cypress/.eslintrc.json, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/reusable/check-sdk-navigation-slide-in-callback-test.js, test/extensions/test-extension/package-lock.json, typings.d.ts
Expose new method to `navigator` object.
=> Add sdk.navigator.onSlideInNavigation

lib/api.js, lib/app.js, lib/locations.js, test/unit/api.spec.js, test/unit/app.spec.js, typings.d.ts
=> Clean up alpha leftovers

lib/api.js, lib/navigator.js, package-lock.json, package.json, test/unit/navigator.spec.js, typings.d.ts
Adding in a new method to allow for navigation to app page locations.
=> App page navigation

.circleci/config.yml, test/cypress/support/index.ts
Use latest cypress version without retries.
=> deps: update cypress and remove retries

test/cypress/integration/dialog-extension.spec.ts, test/cypress/integration/entry-editor-extension.spec.ts, test/cypress/integration/field-extension.spec.ts, test/cypress/integration/sidebar-extension.spec.ts
Rely only on test id selectors.
=> fix: update selectors

lib/api.ts, lib/types.ts, test/unit/api.spec.ts
Allow to check access level of a user.
=> Add access API

cypress.json, test/cypress/integration/dialog-extension-reusable.spec.ts, test/cypress/integration/dialog-extension.spec.ts, test/cypress/integration/entry-editor-extension-reusable.spec.ts, test/cypress/integration/entry-editor-extension.spec.ts, test/cypress/integration/field-extension-reusable.spec.ts, test/cypress/integration/field-extension.spec.ts, test/cypress/integration/page-extension-reusable.spec.ts, test/cypress/integration/page-extension.spec.ts, test/cypress/integration/sidebar-extension-reusable.spec.ts, test/cypress/integration/sidebar-extension.spec.ts, test/cypress/support/commands.ts
Disable consent manager the right way.
=> Disable consent manager via localStorage

lib/entry.ts, package-lock.json, package.json, test/unit/entry.spec.ts
This adds metadata if it exists to the `sdk.entry` object.
=> feat(metadata): Add entry metadata to sdk result

lib/types.ts, package-lock.json, package.json
Update types of the IDSapi to match the implementation
=> Update idsapi types

lib/types.ts, package-lock.json, package.json
This makes the EditorWidget not optional inside the `editors` array.
=> Making the EditorWidget non-optional

package-lock.json, package.json
Release bump for https://github.com/contentful/ui-extensions-sdk/pull/335
=> Bump minor version due to parcel replacement

lib/api.ts, lib/space.ts, lib/types.ts, package-lock.json, package.json, test/unit/space.spec.ts
Expose `sdk.space.signRequest` and add type to SpaceAPI
=> feat: add request signing endpoint in space API

lib/types.ts, package-lock.json, package.json
We started to inject env alias ID, expose it in types
=> Add env alias to IdsApi type

lib/navigator.ts, lib/types.ts, test/unit/navigator.spec.ts
This PR adds a new method to the SDK which allows for navigation to the app config screen.
=> feat: add openAppConfig method

.circleci/config.yml
=> chore: Rename NPM_TOKEN to NPM_AUTOMATION_TOKEN

lib/api.ts, lib/types.ts
=> fix: correct type for canEditAppConfig

rollup.config.js
Make PRs that fail to build correctly fail the checks
=> chore: fail checks if build emits errors

lib/navigator.ts, lib/types.ts, test/unit/navigator.spec.ts
Adds two new methods `openEntriesList`, `openAssetsList`
=> feat: add navigate to lists methods

.circleci/config.yml, .gitignore, cypress.json, mocha.reporters.json, mocha.unit-reporters.json, package-lock.json, package.json
With this PR, test reports are stored in CircleCI using `store_test_report`
=> chore: store test reports in Circle CI [EXT-2634]

cypress.json
Unblocking the pipeline for now. We need a proper investigation later.
=> chore: add temporary retry to test suite

lib/field-locale.ts, lib/types/entities.ts, lib/types/entry.types.ts, lib/types/field-locale.types.ts, lib/types/field.types.ts, lib/types/utils.ts, lib/types/validation-error.ts
* added ValidationError type
* removed `Function` for unsubscribe
* used generics for better type safety when setting value
=> feat: improve types for Field & Entry API

lib/types.ts
Add optional dueDate field to the Task entity.
=> types: add due date as a task field

docs/cf-extension-api.js, docs/cf-widget-api.js, docs/tagged/cf-extension-api-v2.0.1.js, docs/tagged/cf-extension-api-v2.0.js, docs/tagged/cf-extension-api-v2.1.0.js, docs/tagged/cf-extension-api-v2.1.js, docs/tagged/cf-extension-api-v2.js
Reverts contentful/ui-extensions-sdk#764
=> chore: [] remove tracking for old uie assets

lib/types/entry.types.ts, package-lock.json, package.json
Adding a new optional dueDate field to the Task entity. Applying changes from master to canary branch.
=> feat: add due date as a task field type

lib/types/api.types.ts
Another location where I missed using ContentTypeAPI...
=> fix: set ContentTypeAPI in SharedEditorSDK

lib/space.ts, lib/types/entities.ts, lib/types/space.types.ts, test/unit/space.spec.ts
[Last missing PR in exp-sdk](https://github.com/contentful/experience-packages/pull/1109)
=> feat: add interface for space.getTeams to v4 [HOMER-84]

lib/types/api.types.ts
=> fix: [] Optional adapter

lib/types/entities.ts, lib/types/field-locale.types.ts, lib/types/index.ts, lib/types/space.types.ts, lib/types/utils.ts, package-lock.json, package.json, tsconfig.json
Also, introduces `SerializedJSONValue` for `setValue`
=> fix: missing space types and SerializedJSONValue

lib/entry.ts, lib/types.ts
Add proper typings for a metadata of entry, return `getMetadata` and `onMetadataChange` methods at `createEntry` resulting object.
=> feat: [EXT-2242] Add typings and expose metadata methods

lib/types/api.types.ts, lib/types/entities.ts, lib/types/entry.types.ts, lib/types/index.ts, lib/types/utils.ts
=> fix: Metadata type imports

.github/workflows/dependabot-approve-and-request-merge.yml
=> chore: auto merge dependabot

test/cypress/integration/reusable/open-asset-test.ts, test/cypress/utils/paths.ts
New expected behavior in the new version of user_interface
=> chore: update verification paths

lib/types.ts
=> fix: create upload types

lib/api.ts, lib/types.ts
Forgot to pass patch whenever it's available in the message
=> fix(AccessAPI): include patch in postMessage [EXT-3041]

lib/api.ts, lib/types/api.types.ts, lib/types/index.ts
Ah, here we go again - adding patch to canary
=> fix: add Patch in postMessage for canary branch [EXT-3041]

lib/types/index.ts
Noticed that this type isn't exported - which is stopping me from being able to upgrade the package to v4.0.0 in another project.
=> feat: [] export validation error type

lib/types/validation-error.ts
=> fix: LinkContentTypeValidationError contains a list of content types

lib/space.ts
Explicitly state we are going to remove Space API and its method from v5 on
=> docs: EXT-3234 explicitly state 5.0.0 deprecation plan

lib/types/api.types.ts
=> [EXT-3772] feat: Update IdsAPI type

lib/types/entry.types.ts
Fix the getTasks method - make the param optional.
=> feat: add query param to getTasks

package-lock.json, package.json
=> feat: ui-config updates [EXT-3738]

lib/api.ts, lib/locations.ts, lib/types/api.types.ts, lib/types/index.ts, test/unit/api.spec.ts
Same as #1322 but merging to `master`.
`canary` is not clean, so this is a recreation of the previous PR to make a nice release.
=> feat: add home location [EXT-3684]

.contentful/vault-secrets.yaml
=> chore: setup vault [EXT-4071]

.circleci/config.yml
Introduce usage of vault for CI
=> chore(ci): use vault secrets [EXT-4071]

.github/dependabot.yml, package-lock.json, package.json
Pinning semantic release as v20 is on node 18 while we're running v16.
=> chore: pin semantic release [EXT-4264]

lib/entry.ts, lib/types/api.types.ts, lib/types/entry.types.ts, lib/types/index.ts, lib/types/utils.ts
With the GA of workflows, we expose automationTags for entries via sys.
=> feat: expose automation tags on entry.sys []

lib/types/cmaClient.types.ts
Adding already supported app sdk entities  into app sdk types for anyone to use.
=> feat(Entities): add more supported entities to app sdk's cma [EXT-4359]

lib/types/cmaClient.types.ts
Exposing the new function `createWithResponse`, `getCallDetails` added for app action call.
=> fix: exposed createWithResponse function[]

lib/field-locale.ts, lib/field.ts, lib/types/field-locale.types.ts, lib/types/field.types.ts
Expose field name in related APIs for convenience.
=> feat: [EXT-3265] Add field name prop

lib/api.ts, lib/cma.ts, lib/types/api.types.ts, package-lock.json, package.json, rollup.config.js, test/unit/api.spec.ts, test/unit/cma.spec.ts
Including `contentful-management` dependency in a bundle to support legacy UI Extensions.
=> feat: [EXT-3599] Bundle contentful-management with app-sdk. (Fixing previous PR)

lib/api.ts, lib/cma.ts, lib/types/api.types.ts, package-lock.json, package.json, rollup.config.js, test/unit/api.spec.ts, test/unit/cma.spec.ts
Including contentful-management dependency in a bundle to support legacy UI Extensions.
=> feat: [EXT-3599] Bundle contentful-management with app-sdk. (Third attempt) 

README.md
Adding steps to create a canary release
=> docs(skip ci): [] Canary release steps

tsconfig.json
Make developers happy because typescript is properly resolving modules
=> chore: configure ts module resolution to nodenext

lib/navigator.ts, lib/types/index.ts, lib/types/navigator.types.ts, test/unit/navigator.spec.ts
Removes `navigator.openPageExtension`
=> refactor: removes `navigator.openPageExtension` [EXT-4621]

lib/navigator.ts, lib/types/navigator.types.ts, test/unit/navigator.spec.ts
=> feat: add options for openEntriesList and openAssetsList [EXT-4514 EXT-4618]

lib/types/index.ts
Expose new filtering typings for openEntriesList and openAssetsList methods. We will need these types in user_interface later.
=> chore: [EXT-4670][EXT-4671] Expose filtering options types

.github/CODEOWNERS, CODEOWNERS
=> chore: Update CODEOWNERS []

tsconfig.json
=> fix: use tsc ESNext/Node module/resolution options []

.circleci/config.yml, package-lock.json, package.json
This version of dependabot requires a slightly bumped version of node in circle
=> [] fix: semantic version + circleci npm version

.circleci/config.yml, README.md, lib/api.ts, lib/app.ts, lib/channel.ts, lib/cma.ts, lib/editor.ts, lib/entry.ts, lib/field-locale.ts, lib/field.ts, lib/index.ts, lib/initialize.ts, lib/space.ts, lib/types/api.types.ts, lib/types/dialogs.types.ts, lib/types/navigator.types.ts, lib/types/space.types.ts, lib/window.ts, package.json, test/unit/channel.spec.ts, test/unit/entry.spec.ts, test/unit/field-locale.spec.ts, test/unit/field.spec.ts, test/unit/initialize.spec.ts, test/unit/space.spec.ts
update references from master to main
some linting fixes
=> chore: Update branch name from master to main []

.github/CODEOWNERS
=> chore: [MEC-5742] - Update CODEOWNERS

catalog-info.yaml
=> chore: add ci alerts []

.github/dependabot.yml, package-lock.json, package.json
=> fix: non compatible test deps [NONE]

.circleci/config.yml
=> fix: [] add NPM token to .npmrc in CI

lib/types/index.ts
=> feat: export allowed resources error types

lib/types/index.ts, lib/types/utils.ts
Expose type for cursor-based collection response.
=> feat: add type for cursor-based collection responses

.husky/pre-commit
fix husky - see https://github.com/typicode/husky/issues/1472#issuecomment-2236089807
=> fix: husky pre-commit []

lib/entry.ts
=> feat: bump to deploy []

lib/entry.ts
=> feat: bump version for deploy []
