contentful/ui-extensions-sdk

examples/alloy-editor/widget.json, examples/chessboard/widget.json, examples/json-editor/widget.json, examples/json-form-editor/README.md, examples/json-form-editor/src/json-form-editor.js, examples/json-form-editor/widget.json, examples/rating-dropdown/README.md, examples/translate/widget.json
The `contentful-widget` cli would reject localhost urls without "/" concluding the domain. With this change the examples should work out of the box again.
=> Fixes widget.json `src` for example widgets

examples/slug/Makefile, examples/slug/app.js, examples/slug/index.html, examples/slug/package.json
Fix:
- Wrong method names
- Race conditions due to api not being loaded before the widget entry point was called
- How duplicates were looked up (this wasn't working at all)
Refactor:
- Rewrite using ES2015 to keep it consistent with other widgets
- Abstract away change handling into a function
- Rename functions based on what they do
- Added comments
=> Slug widget: Fix broken slug editor

lib/api/channel.js, test/unit/channel.spec.js
Some method calls only want to indicate completion by returning a promise that resolves to `undefined`. We now handle that case.
=> fix: Handle 'undefined' call result

Makefile, webpack.config.js
Make naming consistent since widgets are now called extensions
everywhere.
=> Switch to new taxonomy

webpack.config.js
This allows us to host all previous versions of the SDK.
=> Generate dist file with version tag

CHANGELOG.md, docs/ui-extensions-sdk-frontend.md, lib/api/channel.js, lib/api/field-locale.js, lib/api/index.js, lib/api/initialize.js, test/unit/channel.spec.js, test/unit/field-locale.spec.js, test/unit/initialize.spec.js
This PR adds the `fields.validations` property and the `fields.onSchemaErrorsChanged` signal.
In addition we refactored the communication channel and provided a mechanism of initializing signal values before passing control to the user.
_Review commit by commit_
=> Validations and error callback

.npmignore, DEVELOPING.md, package.json
Keeps the package size small and prevents leaking unwanted files when publishing.
=> Only pack necessary files for NPM

DEVELOPING.md, Makefile, README.md, docs/ui-extensions-sdk-frontend.md, webpack.config.js
* Do not create distributions tagged with versions anymore
* Do not update the file distribution in `./docs`.
* We keep the old dist files on GH Pages for backwards compatibility
* Document using unpkg.com to get distributed files
=> Switch to unpkg CDN

CHANGELOG.md, docs/ui-extensions-sdk-frontend.md
We don’t need to change the SDK implementation since we just take the object we get from the web app. If that object includes more information then we expose it.
Closes #155
=> Add docs for exteneded `user` API

README.md
Example UI Extensions are in a separate repo, there has been no link provided in the `README.md`.
=> Insert link to example UI Extensions repo

package.json
Until now, many actual dev dependencies were located in `dependencies`. While this is also not ideal with regards to the downloaded package's size, in our case it even lead to conflicts since the (pretty old) `webpack` and `babel-loader` packages were "overwriting" newer versions from other dependencies (I don't yet understand why npm would do this, to be honest).
=> Moved some dependencies into devDependencies

CHANGELOG.md, docs/ui-extensions-sdk-frontend.md, lib/api/dialogs.js, package.json, test/unit/dialogs.spec.js
`alert`, `confirm`, `prompt` for UI Extensions, following the visual style of the Contentful Web App.
=> Simple dialogs (alert, confirm, prompt)

CHANGELOG.md, docs/ui-extensions-sdk-frontend.md, lib/api/field.js, lib/api/index.js, package.json, test/unit/field.spec.js
- Expose locale names: `locales.names`.
- Expose field type and validations: `entry.fields[id].type`,
`entry.fields[id].validations`.
=> Expose more info

lib/api.js, lib/index.js, lib/initialize.js, test/helpers.js, test/unit/api.spec.js, test/unit/window.spec.js
Allows to define how the Extension API is built.
Will allow to have different API depending on the location of an extension.
Backwards compatible, if the Web App don't initialize connection with the `location` parameter the default of `entry-field` is used.
This PR includes definition of the API for `entry-sidebar` location (basically: not including the `field` object)
=> Prepare for extension locations

lib/field-locale.js, lib/field.js, test/unit/field-locale.spec.js, test/unit/field.spec.js, typings.d.ts
Expose `required` and `items`(`.type .linkType .validations`) on both `Field` and `FieldLocale instances`
=> Expose field "required" and "items" properties

lib/api.js, lib/app.js, lib/locations.js, package-lock.json, package.json, test/helpers.js, test/unit/api.spec.js, test/unit/app.spec.js, typings.d.ts
adds a new `platformAlpha` namespace with the following API:
- `sdk.platformAlpha.app.isInstalled(): boolean`
- `sdk.platformAlpha.app.getParameters(): null | object`
- `sdk.platformAlpha.app.getCurrentState(): null | object`
- `sdk.platformAlpha.app.onConfigure(handler): void`
=> Add "platformAlpha" namespace

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-asset-test.js, test/cypress/integration/reusable/open-entry-test.js, test/cypress/integration/reusable/open-page-extension-test.js, test/cypress/integration/sidebar-extension.spec.js
Next tests were refactored to call sdk methods directly and not through DOM-elements: 
- dialog-extension.spec.js
- entry-editor-extension.spec.js
- field-extension.spec.js
- page-extension.spec.js
- sidebar-extension.spec.js
=> Refactor tests

test/cypress/integration/dialog-extension.spec.js, test/cypress/integration/entry-editor-extension.spec.js, test/cypress/integration/field-extension.spec.js, test/cypress/integration/page-extension.spec.js, test/cypress/integration/reusable/open-notifications-test.js, test/cypress/integration/sidebar-extension.spec.js
Added tests, which verify, that notification messages are displayed, when methods sdk.notifier success and fail are called.
=> Added sdk.notifier success and fail methods tests

typings.d.ts
Fixes a typo in the `CollectionResponse` type name.
=> Fix CollectionResponse type name

lib/space.js, package-lock.json, package.json, test/unit/space.spec.js, typings.d.ts
Add a new `getEditorInterfaces` method to `space` to retrieve all editor interfaces for all content types within a given environment.
- [✓] Tests are added
- [✓] Tests are passing
- [✓] Typescript typings are added
=> Add getEditorInterfaces method to space

typings.d.ts
SDK's `init` often forces you to use `as` assertion, even when you know it would only be, for example, `FieldExtensionSDK`.
```ts
init(sdk => {
const initialValue = (sdk as FieldExtensionSDK).field.getValue()
render(<App sdk={sdk as FieldExtensionSDK} initialValue={initialValue} />, root)
})
```
I want to use generic to express it would only be a specific type of SDK.
```ts
init<FieldExtensionSDK>(sdk => {
const initialValue = sdk.field.getValue()
render(<App sdk={sdk} initialValue={initialValue} />, root)
})
// Or even...
init<FieldExtensionSDK | SidebarExtensionSDK>(sdk => { ... })
```
=> Making init() generic

lib/api.js, package-lock.json, package.json, test/cypress/integration/fixtures/locales-data.json, test/cypress/integration/reusable/open-sdk-locales-data-test.js, test/extensions/test-extension/package-lock.json, test/unit/api.spec.js, typings.d.ts
=> Add locale fallbacks

lib/api.js, package-lock.json, package.json
We called `createApp` twice which is fine until... you realize channel handlers are registered twice in this case. It still works fine... most of the time. Depending on timing of messages the SDK may end up in a weird state.
Solution: create `app` namespace once and reuse the same reference.
=> Fix app handler registration

package-lock.json, package.json, typings.d.ts
ContentType.fields is not an object but an array.
Added optional deletedVersion and archievedVersion properties.
=> Improve typescript typings 2

package-lock.json, package.json, typings.d.ts
Overload entry field `onValueChanged` and `onIsDisabledChanged` methods.
=> Add entry field method overloads

package-lock.json, package.json, typings.d.ts
Update type definitions to reflect all possible options for `selectSingleAsset` and `selectMultipleAssets`.
=> Extend entity selector options

package-lock.json, package.json, typings.d.ts
Return NavigatorSlideInfo from slide-in `navigator` methods.
=> Add slide in information

lib/navigator.js, package-lock.json, package.json, typings.d.ts
Adds a new method: `sdk.navigator.openBulkEditor`.  Closes https://github.com/contentful/ui-extensions-sdk/issues/250
=> feat: add open bulk editor method

lib/app.js, package-lock.json, package.json, test/unit/app.spec.js
Removing the guard in the `onConfigure*` handlers gives more flexibility to devs.
=> remove guard in onConfigure* handlers

lib/initialize.js, test/unit/initialize.spec.js
Allow to create custom APIs. The creator function gets raw channel and init data and should return an object of methods.
=> Inject custom API creator

lib/field.ts, lib/types.ts, test/unit/field.spec.ts
In order to use our Field Editor components with the Entry editor SDK, we need to have some way to get a `fieldLocale` object from an entry. I think the easiest way to do this is to make it possible to extract a fieldLocale from a field. 
Basically this PR just makes an existing private method public.
One thing that I'm not sure of, is how it's possible to determine from the Entry API which locale is currently being edited.
=> feat: allow creation of field locale instance from field

cypress.json
Increase the `defaultTimeout` to 15s to avoid inconsistent ui integration tests
=> fix(ui-integration-suite): increase cypress default timeout to 15s [EXT-1913]

lib/field.ts
We actually need these info types now that we are able to get the fieldLocale instance
from the field. 😨
=> fix: pass through required properties to fieldLocale from field

lib/types.ts
This change makes the `PublicActionStatus` useable in code. See how typescript differentiates between these two approaches in this example:
https://www.typescriptlang.org/play/index.html#code/KYOwrgtgBAglDeUDOYDGrhKVAvFARCupkvlAL4CwAUDagPYhIAuUAHrrAHREZY11GLKKEhQAQgmRo+2PIRkkyVWtQZNWAT07ieirEA
=> making PublicActionStatus useable in code

lib/types.ts
This updates the typings for scheduled `ScheduledAction` to use a string for its date value.
I've included JSDocs to show up in most editors to indicate the format.
=> Updating the scheduled date typings to be strings

lib/field-locale.ts, test/unit/field-locale.spec.ts
This change makes it possible to handle errors inside of entry extensions, by following a similar approach that was used to make `isDisabled` available in entry extensions.
This shouldn't be merged until we're confident that adding these events to user interface hasn't caused any issues.
=> feat: listen to new schemaerrorschangedforfieldlocale events

lib/types.ts
While looking at the difference between FieldAPI and EntryFieldAPI I noticed that the type definitions had some inconsistencies. For these properties in particular the FieldAPI definition was incorrect.
I guess this is a breaking change - as it might cause type errors for some users?
=> fix(EntryFieldAPI): fix incorrect type definition

.circleci/config.yml
To get faster feedback in case of flakiness of the integration tests, we run the integration test now every 2 hours.
=> chore(test): run integration tests every 2 hours

test/cypress/integration/dialog-extension-reusable.spec.ts, test/cypress/integration/dialog-extension.spec.ts, test/cypress/integration/entry-editor-extension-reusable.spec.ts, test/cypress/integration/entry-editor-extension.spec.ts, test/cypress/integration/field-extension-reusable.spec.ts, test/cypress/integration/field-extension.spec.ts, test/cypress/integration/page-extension-reusable.spec.ts, test/cypress/integration/page-extension.spec.ts, test/cypress/integration/sidebar-extension-reusable.spec.ts, test/cypress/integration/sidebar-extension.spec.ts
In order to improve stability for the test suite for the `user_interface` the long running test suites are splitted into specific tests and reusable tests. Cypress slows down on long running tests and make the integration tests on certain environments timeout. Splitting it into multiple tests suites avoids this problem.
=> fix(test): split tests in specific and reusable test suites

lib/dialogs.ts, lib/types.ts
In order to avoid confusion with extensions and apps this PR introduces a new method for the dialogs API to open the `current` extension or app in a dialog. 
- update field editors to make use of this new method
- add documentation for the `openCurrent` method
=> feat: add openCurrent method to dialogs api

.circleci/config.yml
In order to get more confidence with extension sdk we bump the cron job to run every hour.
=> chore: bump cron job for integration tests

test/cypress/integration/reusable/open-asset-test.ts
A `test-id` changed for the workbench back button. This PR updates the test id.
=> fix: update test-id to fix broken tests

lib/types.ts, package-lock.json, package.json
Adding types for the optional metadata object found on `sdk.entry.metadata`.
=> Metadata typings

lib/app.ts, lib/types.ts, test/unit/api.spec.ts
This change is meant to make the App SDK able to fetch the state to be manipulated and provided to the `targetState` portion of the return value of the `onConfig` hook.
1. Get the current state by using `getCurrentState` method
2. Modify the state to introduce/remove/change where the app is to be rendered
3. Return the modified state as `targetState` in the `onConfiguration` callback
[Reference](https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#register-an-app-configuration-hook)
=> feat: add getCurrentState method to uie-sdk app api

lib/types.ts
It's possible for the return value to be null before installation.
=> Fixing `getCurrentState` return value.

lib/app.ts
The app handlers such as `onConfig` swallow errors and `return false`. I've added `console.error` to keep the functionality the same while exposing errors that happen when these handlers are run for a better debugger experience.
When an error does occur, the handlers `return false` like mentioned about but the installation or save doesn't proceed. This is why I've opted to simply add `console.error` instead of trying to completely change the behavior of these handlers.
=> console.error when error happens in app handler.

lib/types.ts, package-lock.json, package.json
The `space.waitUntilAssetProcessed` was wrong as it is async in the implementation but sync in the typing.
=> chore: fix space.waitUntilAssetProcessed typing

lib/api.ts, lib/types.ts, package-lock.json, package.json
I noticed that the type for `AppExtensionSDK` doesn't match the underlying implementation, as the type incorrectly includes an `entry` and `contentType` key. This error also applied to some of the other SDK types.
This PR just fixes that type error.
=> fix: remove entry and contenttype key from baseextensionsdk

lib/types.ts
Another issue I discovered whilst trying to implement the AppSdk, these types didn't actually match the implementation, as onConfigure and onConfigurationComplete don't return anything!
=> fix: make api configuration functions types match implementation

lib/types.ts
=> chore: deprecate entryAPI.metadata

lib/types.ts
As mentioned in #321, if an entry is deleted during a `navigator.openEntry` call with the `waitForClose` property, the promise is not resolved.
We should not resolve with an outdated entry, but also can not resolve with an nonexistent entry. For this reason we need to change the promise return type to allow for a missing entry in case it has been deleted during user interaction.
=> fix: make entity optional on navigator response

lib/types.ts
The recent [migration to typescript strict mode](https://github.com/contentful/ui-extensions-sdk/pull/345) has wrong return values on some methods, and is missing an overload.
=> fix: EntryAPI and EntryFieldAPI return value typing

lib/initialize.ts, module-declaration.d.ts
This PR tries to make it more obvious what's going wrong when ui-extension-sdk is used outside of Contentful. It shows an error when init is called outside of an iframe
The link doesn't currently point to a specific question in the FAQ - I intend to update the FAQ with that information.
=> feat: log error if it appears app is running outside of iframe

.dependabot/config.yml, CHANGELOG.md, package.json
* Remove scope from semantic release commit messages and dependabot commit messages. For consistency as most of our commit messages don't have a scope
* Because of missing git tags, the changelog was not created correctly. I manually fixed it. Also, I'll add the missing git tags.
* We didn't add the @semantic-release/npm package and therefore the version was not bumped. This is now fixed. The publish still happens using our custom script.
=> chore: Multiple fixes to semantic release

lib/api.ts, lib/space.ts, lib/types.ts
Make the signRequest function non optional, as it is checked at runtime - and we want to provide a consistent API surface
=> fix: make signRequest non optional

lib/api.ts, lib/types.ts, test/unit/api.spec.ts
=> feat: add canEditAppConfig method

rollup.config.js
If you don't use a bundler you can simply import the library in your html file and use it with 
```javascript
window.contentfulExtension.init(...)
```
We want to make it possible to _also_ use `window.contentfulApp`. Unfortunately, it is not possible to export multiple variables using rollup. A workaround is using the `footer` property:
> Code to insert at end of bundle (outside wrapper)
This seems to be the recommended approach: https://github.com/rollup/rollup/issues/553#issuecomment-202166713
I tested it with the following code:
```html
<script src="dist/cf-extension-api.js"></script>
<script>
console.log(window.contentfulApp);
console.log(window.contentfulExtension);
</script>
```
=> feat: export module as contentfulApp

README.md
UIE SDK -> App SDK
We keep the old name but prioritize the new one.
=> docs: rename UIE SDK to App SDK in readme

.circleci/config.yml
We currently cache the `node_modules` folder but actually never use it.
After restoring it, we immediately drop it using `npm ci`. Therefore, I decided to fully drop the cache and always clean install the dependencies.
That way we also avoid issues with updating and resetting `package-lock.json`.
This should improve the total build time by 10-20s (just guessing)
As `npm ci` in some cases only takes a few (<30s) it's also not really worth caching and restoring the whole thing.
=> chore: remove dependency cache from ci

README.md
The current link points to a missing page.
=> fix: link to App SDK reference

test/cypress/integration/entry-editor-aliased.spec.ts, test/cypress/utils/paths.ts, test/integration/index.ts, test/integration/local.ts, test/integration/tasks/create-configuration-files.ts, test/integration/tasks/create-new-environment.ts, test/integration/tasks/delete-new-environment-alias.ts
Adds a test for the entry editor location to make sure the SDK is hitting the correct endpoints in aliased environments.
If we're happy with this approach, we might want to add similar tests for each SDK/location as a follow up
=> feat: test that SDK respects alias

lib/types/index.ts, lib/types/space.types.ts, lib/types/utils.ts
* expose `withId`
* capture the following cases with typings:
* create with only `sys.id` specified (e.g. Content Type)
* create with either at least `sys.id` or no `sys` at all (e.g. Entry)
=> feat: expose WithId

test/cypress/integration/dialog-extension-reusable.spec.ts, test/cypress/integration/dialog-extension.spec.ts, test/cypress/integration/entry-editor-extension-reusable.spec.ts, test/cypress/integration/entry-editor-extension.spec.ts, test/cypress/integration/entry-editor-on-value-changed.spec.ts, test/cypress/integration/field-extension-reusable.spec.ts, test/cypress/integration/field-extension.spec.ts, test/cypress/integration/initialize.spec.ts, test/cypress/integration/reusable/open-entry-test.ts, test/cypress/integration/sidebar-extension-reusable.spec.ts, test/cypress/integration/sidebar-extension.spec.ts, test/cypress/support/commands.ts, test/extensions/test-extension/package-lock.json
To prevent some flaky integration tests failing when reaching the rate limit on visiting the entry, this adds a command to visit entries and when failed with a 429 it waits 1second and revisits the page.
=> test: retry visit on integration tests

lib/types/api.types.ts, lib/types/entities.ts, lib/types/index.ts
Add better types for User API, capturing the fact that `roles` is an incomplete (does not include permissions and policies) resolved `Role` list, rather than a list of links.
=> feat: better typings for user API

lib/app.ts, lib/types/app.types.ts, lib/types/index.ts
> The callback provided can be synchronous or asynchronous.
> If the callback returns false, throws or returns a promise which will be eventually rejected, the process is aborted and no changes are made. This way the app can validate its state and user inputs before continuing.
=> fix: update onConfigure type to match reference

lib/types/api.types.ts
We are exposing the public types and not the types from CMA. The CMA data can only be fetched using `space.getContentType(id)`
=> fix: change ContentType API to public type

lib/types/entry.types.ts
Add the `assignedToType` filed to the TaskInputData so the task could be assigned to other entity types but the User.
Make this field optional for backward compatibility.
=> feat: add type parameter to create task input data

test/cypress/integration/reusable/open-asset-test.ts
Fixes some flakiness in the integration test.
Instead of setting a variable and checking if this variable is set after clicking the back button, this check is made more explicit by checking if the slide-in is really gone and no longer visible when the callback was called.
=> test: [] check for slide in visibility instead of is clicked variable

test/cypress/integration/reusable/open-asset-test.ts
Fixes one of the slide-in asset editor tests that was failing after some internal changes in the web app. 
With those changes the callback returned from `openAsset()` with `waitForClose: true` option now triggers immediately after `clickSlideInClose()` and executed in the the same cy command context, prohibiting calling another cy command inside the promise. It caused the ["Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise."](https://docs.cypress.io/guides/references/error-messages#Cypress-detected-that-you-returned-a-promise-from-a-command-while-also-invoking-one-or-more-cy-commands-in-that-promise) error.
=> test: fix openAsset waitForSlideIn test

.circleci/config.yml, test/cypress/integration/initialize.spec.ts, test/integration/index.ts, test/integration/tasks/copy-entries.ts
Changes:
* `set -e` is unneeded: CircleCI already runs the shell with that flag on
* I wanted to streamline the setup across environments removing the third "staging" environment we use for tests. This would require changes which might be breaking for other peoples' (user, internal) workflows. Reverted it to its previous state
* If cleanup upon failure fails itself, the test shouldn't be green 🙃
=> fix: copy entries to target environment

test/cypress/utils/remove-variable-data.ts
For the tasks EAP we pass in a `teamMemberships` property to the `sdk.user` object but do not expose public types for it. This is only temporary until we implemented a proper authZ solution for the tasks app. This PR just ignores the `teamMemberships` property for the integration tests.
=> chore: ignore teamMemberships property for integration tests [HOMER-151]

lib/types/app.types.ts
We currently get the following error when updating to app sdk v4 in a fresh CCA app
```
Type 'Promise<{ parameters: AppInstallationParameters; targetState: AppState | null; }>' is not assignable to type 'OnConfigureHandlerReturn'.
Type 'Promise<{ parameters: AppInstallationParameters; targetState: AppState | null; }>' is not assignable to type 'Promise<{ parameters?: KeyValueMap | undefined; targetState?: AppState | undefined; }>'.
Type '{ parameters: AppInstallationParameters; targetState: AppState | null; }' is not assignable to type '{ parameters?: KeyValueMap | undefined; targetState?: AppState | undefined; }'.
Types of property 'targetState' are incompatible.
Type 'AppState | null' is not assignable to type 'AppState | undefined'.
Type 'null' is not assignable to type 'AppState | …
```
=> fix: allow OnConfigureHandlerReturn props to be null [EXT-2869]

docs/run-integration-tests.md, test/integration/index.ts, test/integration/tasks/delete-stale-entries.ts, test/integration/tasks/delete-stale-environments.ts, test/mocks/entries.ts, test/unit/delete-stale-entries.spec.ts, test/unit/delete-stale-environments.spec.ts
With this PR we delete stale entries from `master-test` before every run. In theory these should be deleted after the tests finish, but in some cases CI crashes and some leftovers remain in the `master-test` environment. The implementation is almost identical to removing stale environments.
The stale environment removal task had a few implementation issues:
- You can't use `.forEach` with async functions as we cannot `await` for `forEach` to finish with all promises. I therefore rewrote this to a `for ... of ...`
- We are using the plain cma client here which means that we cannot call `environment.delete()` or `entry.delete()`. I adjusted the code to use the plain client syntax for deletion.
=> chore: remove stale entries before each run and fix envs

lib/types/api.types.ts, lib/types/dialogs.types.ts, lib/types/field-locale.types.ts
We call the library App SDK and apps are the latest way to extend Contentful. We should therefore also not refer to legacy extensions in our comments.
=> fix: adjust comments to mention apps instead of extensions

test/cypress/integration/entry-editor-permission.spec.ts
error codes can be in both ways returned
=> test: [] permission integration test fix

lib/types.ts
Instead of Patch as an action, we use update but pass a patch as an option instead
=> fix(AccessSDK): patch is not a supported action [EXT-3041]

lib/types/api.types.ts
Add support for checking patches for all entities supported in access sdk
=> feat(AccessAPI): add support for JSON patches in access sdk [EXT-3041]

lib/types/app.types.ts
Small change to the `OnConfigureHandlerReturn` type. That way you can now write code like
```typescript
const onConfigure: async (): OnConfigureHandlerReturn => {
...
}
```
that was previously not possible because of
> Type 'OnConfigureHandlerReturn' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
Also it was previously not valid to return `Promise<false>`
=> fix: remove Promise<...> type from OnConfigureHandlerReturn [EXT-3082]

lib/types/validation-error.ts
In upgrading another package I spotted that this type is wrong.
=> fix: [3161] use correct type for conflicting errors

.circleci/config.yml
`circleci/node` is a legacy image and therefore doesn't have the latest node versions
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/
=> chore: use cimg/node instead of circleci/node

.github/dependabot.yml, .husky/pre-commit, package-lock.json, package.json
We didn't update to v5 because of the changed license. Husky 7 uses MIT again, so we can update.
=> chore: update husky to v7

lib/initialize.ts, test/unit/initialize.spec.ts
With this PR we ensure that only a single SDK instance exists within an app.
This fixes an issue where multiple SDKs subscribe and respond to an event sent from the host application. E.g. the `sdk.app.onConfigure` hook.
This might be a breaking change if someone decides to mutate the returned SDK. With this change, the mutation would also be returned for all other `init` calls. I assume only very few people do this, so this is only a patch release.
=> fix: return same SDK instance when calling `init` multiple times [EXT-3497]

lib/types/api.types.ts
Previously the IDs API type for the FieldExtensionSDK actually excluded field specific ids. This PR fixes that issue.
Error that we saw previously:
=> fix: [EXT-3363] use correct IDS api for fields

lib/types/api.types.ts, lib/types/dialogs.types.ts
The previous type we used in the parameters API would not allow you to read any properties. This PR brings the type in line with the return value of the `getParameters` method.
=> fix: [] improved types for ParametersAPI

lib/types/navigator.types.ts
`options` param of `openNewAsset` is not optional, but object's internal fields are. That forces to pass empty object if `slideIn` prop not needed. Fixing this.
=> fix: [] Make openNewAsset options param optional

lib/api.ts, lib/types/api.types.ts, test/unit/api.spec.ts
We want to add support for warning notifications in order to have this as outcome:
`field-editors` uses the App SDK in order to send notifications, but we only support `success` and `error` notifications, which is not ideal for our user case.
=> feat: add warning notification support [SHE-785]

lib/types/api.types.ts, lib/types/entities.ts
In order to call `access.can` inside the workflows marketplace app, we need to update the apps SDK so that `WorkflowDefinition` is typed as a `PatchEntity`
=> feat: added worflowdefinition type to exported entities and to api.types

lib/types/index.ts
Last PR did not export Workflow Definition from the `types/index` file
=> feat: exported workflow definition type

lib/channel.ts
Currently, the `init` method does not have a message id or params which causes issues as all other messages do. This PR adds an id and an empty `param` array.
=> fix: add missing properties to new `init` method [EXT-3817]

lib/types/utils.ts
The type `ContentEntityType` currently has a value of `'Entry' | 'Asset' | string`, which the TypeScript compiler aggresively reduces to just `string` since both `'Entry'` and `'Asset'` are subtypes of `string`. This PR forces the compiler not to reduce the union, which also makes autocomplete work for the literals we want to allow 🙂 
There are ways to avoid the reduction by using `string & {}` in the union instead of just `string`. This makes the compiler treat the literals and the string type as separate, since the literals don't inherit from `string & {}`. `type-fest` provides a helper for this type that I've used in this PR.
More information and discussion in this TS issue: https://github.com/microsoft/TypeScript/issues/29729
=> fix: make ContentEntityType more specific

.circleci/config.yml, .contentful/vault-secrets.yaml
It's not required to install the dependencies
=> chore: do not use `npm-read` secret

.circleci/config.yml, .contentful/vault-secrets.yaml
We want to use ecosystem-bot instead of wydah-gally
=> chore: use ecosystem bot for releases

.circleci/config.yml
`workflows.version` is deprecated since config version 2.1: https://discuss.circleci.com/t/circleci-2-1-config-overview/26057
=> chore: remove workflows version number

lib/api.ts, lib/types/api.types.ts
In TypeScript projects, a lot of errors can be prevented via types. Our parameters API (installation, instance, invocation) use fixed types (KeyValueMap, SerializedJSONValue) that cannot be customized by the developer. The developer knows exactly which values will be persisted for each of these parameters, so we should allow the developer to build perfect types.
Currently, when using the parameters API, you see a lot of @ts-expect-error, @ts-ignore or type assignments.
```
const sdk = useSDK<ConfigAppSDK<{ foo: string }>>();
const foo = sdk.parameters.installation.foo;
```
```
const sdk = useSDK<DialogAppSDK<KeyValueMap, never, { foo: string }>>();
const foo = sdk.parameters.invocation.bar;
```
=> feat: adds optional types for parameters [EXT-4381]

README.md
Documentation update on `canary` releases
=> docs[skip ci]: Update canary release flow

CHANGELOG.md, lib/dialogs.ts, lib/types/dialogs.types.ts, test/unit/dialogs.spec.ts
Removes:
- `dialogs.openExtension`
- `dialogs.openCurrent`
Renames:
- `dialogs.openCurrentApp` to `dialogs.open`
=> refactor:  removes extensions from Dialog API [EXT-3595]

CHANGELOG.md, lib/navigator.ts, lib/types/api.types.ts, test/unit/cma.spec.ts
Removes: `sdk.ids.extension`
Makes `sdk.ids.app` required
=> refactor: removes extensions from IDs API [EXT-3597]

lib/types/api.types.ts, lib/types/index.ts
Breaking change to remove the previously deprecated XXXExtensionSDK types
=> [EXT-3204] refactor: Remove XXXExtensionSDK deprecated types

README.md, scripts/publish.js, scripts/shared.js, scripts/verify.js
App SDK v5 won't support UI Extensions support and here we are removing related naming from npm package.
=> feat: [EXT-3593] Do not publish `contentful-ui-extensions-sdk` to npm

lib/editor.ts, lib/types/api.types.ts, lib/types/app.types.ts, lib/types/entry.types.ts, test/constants.ts
BREAKING CHANGE: removed deprecated props & methods
=> feat: remove deprecated props & methods [EXT-4467]

lib/app.ts, lib/types/api.types.ts, lib/types/app.types.ts
`InstallationParams` are now passed down to `AppConfigAPI`.
=> feat: add generic InstallationParams to AppConfigAPI

lib/api.ts, lib/locations.ts, lib/types/api.types.ts, test/unit/api.spec.ts
removes legacy UI extension `entry-field-sidebar` location
=> feat: removes legacy UI extension `entry-field-sidebar` location

.circleci/config.yml
Semantic release [has been unhappy](https://app.circleci.com/pipelines/github/contentful/ui-extensions-sdk/15579/workflows/9f634436-58da-45db-a284-7611d80343f2/jobs/26466) about our node version on circle for a week[ and is blocking releases](https://github.com/contentful/ui-extensions-sdk/commits/master)
=> fix: node 18.18 for semantic release to work

.gitignore, .npmrc
Removes `.npmrc` at the root to see if the publish step in CI will respect the registry being set [here](https://github.com/contentful/ui-extensions-sdk/blob/main/.circleci/config.yml#L46).
=> fix: remove .npmrc at root to fix publish registry [EXT-5905]

package-lock.json, package.json
Bump CMA.js to latest release and force a new release of app-sdk with dependabot updates.
=> fix: force new release with updated contentful-management []

lib/entry.ts, test/unit/entry.spec.ts
- Enhanced makeEntryAPI to accept a release parameter.
- Updated createEntry function to handle the release context, throwing errors for unsupported publish/unpublish actions in release mode.
=> feat(api): add release parameter to entry API and update createEntry [EXT-6548]

lib/entry.ts, lib/types/entry.types.ts, test/unit/entry.spec.ts
Our initial implementation of ensuring `sdk.entry` behaved "correctly" when used in the context of a release entry depended upon extrinsic context (i.e. the presence of absence of a separate `release` in an additional parameter) vs. intrinsic data (i.e. inspecting `entry` itself and looking for `entry.sys.release.sys.id`. This decision was based partly on an (incorrect) assumption that the entry data provided did not include this data, and using the extra `release` parameter was the only option.
Further research uncovered that the entry data passed to this function _does_ include sys.release, and thus the opportunity exists to provide a more correct implementation.
* Update implementation of `createEntry` to use entry data to determine release state vs. `release` param
* Update types to …
=> refactor: use entry data to discriminate release entries in sdk.entry [EXT-6548]

lib/api.ts, lib/cma.ts, lib/types/api.types.ts
This pull request enhances the `ui-extensions-sdk` to support the "Releases v2" project by ensuring apps are aware of the release context they are operating in. This change specifically addresses ticket [EXT-6547](https://contentful.atlassian.net/browse/EXT-6547).
We are adding the `releaseId` to the `sdk.ids` object when an application is running within a release. This provides developers with a straightforward way to access the current release's ID, enabling them to build release-aware features.
A primary use case for this is to allow an app to fetch data or modify its behavior based on the specific release it's interacting with. This is a foundational requirement for many of the planned features in Releases v2.
[EXT-6547]: https://contentful.atlassian.net/browse/EXT-6547?atlOrigin=eyJpI …
=> Feat/release id [EXT-6547]

lib/api.ts, lib/navigator.ts, lib/types/navigator.types.ts, test/unit/navigator.spec.ts
when an app calls sdk.navigator.openEntry(), in order for us to keep the user in the context of the current release when the entry the app wants to navigate to is in the release we need to:
1. allow skd.navigator api module to become release aware
2. create a function called entryInRelease() that checks to see if the entry being opened is in the release or not so that we can pass a entryInRelease value back up the postMessageChannel for the host app to handle.
=> feat: api, navigator): add optional release parameter to createNavigator so openEntry method could work properly.

lib/api.ts, lib/navigator.ts, lib/types/navigator.types.ts, test/unit/navigator.spec.ts
add back entityInRelease to make user_interface know if the entity should be opened in release context or not.
=> feat: Add entityInRelease back to navigateToContentEntity channel message object  [EXT-6551]

lib/navigator.ts, test/unit/navigator.spec.ts
…entityInRelease
- Updated `createNavigator` to pass `releaseId` and `entityInRelease` to various navigation methods, including `openEntry`, `openAsset`, `openNewEntry`, `openNewAsset`, `openEntriesList`, and `openAssetsList`.
- Enhanced unit tests to validate the behavior of these methods with respect to the release context, ensuring correct handling of entries and assets in relation to the provided release.
- Added scenarios to test the inclusion of `releaseId` and the determination of `entityInRelease` based on the presence of the release.
=> feat(navigator): enhance navigation methods to include releaseId [EXT_6551]

lib/types/navigator.types.ts
- Introduced the `entityInRelease` optional property to the `NavigatorAPIOptions` interface, indicating whether an entity is part of the current release. This enhancement supports improved navigation context handling in relation to releases.
=> feat(navigator): add entityInRelease flag to NavigatorAPIOptions [EXT-6551]

lib/navigator.ts, test/unit/navigator.spec.ts
- Removed the `releaseId` parameter from the `openEntry` and `openAsset` methods in the navigator api since the UX for this method is the same regardless of release context
=> refactor(navigator): remove releaseId from navigation methods [EXT-6551]

lib/types/navigator.types.ts
…ept options [EXT-6551]
- Modified the `openEntriesList` and `openAssetsList` methods in the NavigatorAPI to accept an optional `NavigatorAPIOptions` parameter, enhancing their flexibility for navigation context handling.
[EXT-6551]: https://contentful.atlassian.net/browse/EXT-6551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(navigator): update openEntriesList and openAssetsList to acc… [EXT_6551]

lib/navigator.ts, lib/types/navigator.types.ts, test/unit/navigator.spec.ts
- Updated `openEntry`, `openAsset`, `openEntriesList`, and `openAssetsList` methods to consistently use `releaseId` derived from the release context, removing the `entityInRelease` flag from the parameters.
- Simplified the `NavigatorAPIOptions` interface by removing the `entityInRelease` property.
- Adjusted unit tests to reflect these changes, ensuring correct behavior when navigating with and without a release context.
=> feat: streamline release handling in navigation methods [EXT-6551]

lib/types/dialogs.types.ts
I need to make the functions optional until they are really implemented. this blocked some other PRs/work, that's why this is necessary for now.
=> refactor: made functions optional until implementation [SPA-3218]
